[package]
name = "libfmp"
version = "0.1.0"
authors = ["sceext <sceext@foxmail.com>"]
edition = "2018"

[features]
default = ["fmp_uart"]
crc8 = []
fmp_uart = ["crc8"]
fmp_uart_fmprinter = ["fmp_uart"]
fmp_usb = [""]

[dependencies]
